spring.application.name=scca
server.port=8080
spring.config.import=optional:application-db.properties, \
                     optional:application-ia.properties, \
                     optional:application-logs.properties, \
                     optional:application-jwt.properties, \
                     optional:application-hw.properties